config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  get 'sort', to: 'products#sort'
  resources :products do
    resources :orders, only: %i[new create]
  end

  resources :comments, only: %i[create update destroy]

  resources :orders, except: %i[index new create] do
    member do
      post 'state/:state', to: 'orders#state', as: 'state'
    end
  end
  get 'basket', to: 'orders#index'

  resource :my, only: %i[show update] do
    get 'personal'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :users, only: %i[show index]

  resources :categories, only: %i[show index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  after_create :set_cost

  def set_cost
    update(cost: (product.price * count))
  end

  scope :active, -> { where(state: 'active') }
  scope :ordered, -> { where(state: %w[order sent]) }
  scope :old, -> { where(state: %w[canceled delivered]) }
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[show update edit destroy state]

  def index
    @orders = if current_user.id == 1
                Order.all
              else
                current_user.orders
    end
  end

  def show; end

  def state
    @order.update(state: params[:state])
    redirect_back(fallback_location: root_path)
  end

  def new
    @order = Order.new
    @product = Product.find(params[:product_id])
    redirect_back(fallback_location: root_path) if @product.nil?
  end

  def create
    @product = Product.find(params[:product_id])
    params[:order][:product_id] = @product.id
    @order = current_user.orders.build(order_params)
    if @order.save
      redirect_to basket_path
    else
      render 'new'
    end
  end

  def updated
    if @order.update(order_params)
      redirect_back(fallback_location: root_path)
    else
      render 'new'
    end
  end

  def destroy; end

  private

  def order_params
    params.require(:order).permit(:user_id, :product_id, :count)
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def order
    @order ||= Order.find(params[:id])
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def order_state(order)
    case order.state
    when 'active'
      [
        link_to( 'Підтвердити замовлення', state_order_path(order.id, 'order'), method: :post),
        link_to( '| Видалити', order_path(order.id), method: :delete)
      ].join(" ").html_safe
    when 'order'
      if user_signed_in? && current_user.id == 1
        link_to 'Підтвердити відпралвення', state_order_path(order.id, 'sent'), method: :post
      else
        link_to 'Відмінити', state_order_path(order.id, 'canceled'), method: :post
      end
    when 'sent'
      if user_signed_in? && current_user.id == 1
        link_to 'Відмінити', state_order_path(order.id, 'canceled'), method: :post
      else
        link_to 'Підтвердити доставку', state_order_path(order.id, 'delivered'), method: :post
      end
    when 'canceled'
      "Відмінено #{order.updated_at.strftime("%d %b, %Y o %H:%M")}"
    when 'delivered'
      "Доставленно #{order.updated_at.strftime("%d %b, %Y o %H:%M")}"
    end
  end
end

app/views/orders/_form.html.erb
<div class="p-2 p-md-3 p-lg-5 text-center">

  <h1>Замовлення товару
    <b><%= @product.name%></b></h1>
  <%= simple_form_for(@order, url:product_orders_path)do |f| %>
  <div class="row p-4 text-center align-item-center">
    <div class="col-0 col-md-2">
      </div>
    Кількість:
    <div class="col-4 col-md-2">
      <%= f.input :count ,label: false,input_html: { value: '1',min: '1', step: 'any'} %>
    </div>
    <div class="col-1">
      *
    </div>
    <div id="order_price" class="col-1">
      <%= @product.price%>
    </div>
    <div class="col-1">
      =
    </div>
    <div id="order_cost" class="col-2">
      <%= @product.price%>
    </div>
    грн.
  </div>
  <%= f.button :submit, "Добавити в корзину" %>
<% end %>
</div>

app/views/orders/_order.html.erb
    <tr>
      <td>
        <%=link_to order.product.name , product_path(order.product_id) %>
      </td>
      <td>
        <%= order.count%>
      </td>
      <td>
        <%= order.cost%>
      </td>
      <td>
        Оплата при доставці
      </td>
      <td>
        <%= order.user.city %>
      </td>
      <td>
        <div><%=order_state(order)%></div>
      </td>
    </tr>

app/views/orders/index.html.erb
<div class="p-4">
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-active-tab" data-toggle="pill" href="#pills-active" role="tab" aria-controls="pills-active" aria-selected="true">Активні</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-order-tab" data-toggle="pill" href="#pills-order" role="tab" aria-controls="pills-order" aria-selected="false">Замовленні</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-old-tab" data-toggle="pill" href="#pills-old" role="tab" aria-controls="pills-old" aria-selected="false">Старі</a>
    </li>
  </ul>

<div class="tab-content" id="pills-tabContent">



      <div class="tab-pane fade show active" id="pills-active" role="tabpanel" aria-labelledby="pills-active-tab">
        <table class="table">
          <thead>
            <tr>
              <th>Назва</th>
              <th>Кількість</th>
              <th>Ціна</th>
              <th>Оплата</th>
              <th>Адрес доставки</th>
              <th>Дії над замовленням</th>
            </tr>
          </thead>
            <tbody>
              <%= render @orders.active%>
            </tbody>
        </table>
      </div>
      <div class="tab-pane fade" id="pills-order" role="tabpanel" aria-labelledby="pills-order-tab">
        <table class="table">
          <thead>
            <tr>
              <th>Назва</th>
              <th>Кількість</th>
              <th>Ціна</th>
              <th>Оплата</th>
              <th>Адрес доставки</th>
              <th>Дії над замовленням</th>
            </tr>
          </thead>
            <tbody>
              <%= render @orders.ordered%>
          </tbody>
        </table>
      </div>
      <div class="tab-pane fade" id="pills-old" role="tabpanel" aria-labelledby="pills-old-tab">
        <table class="table">
          <thead>
            <tr>
              <th>Назва</th>
              <th>Кількість</th>
              <th>Ціна</th>
              <th>Оплата</th>
              <th>Адрес доставки</th>
              <th>Дії над замовленням</th>
            </tr>
          </thead>
            <tbody>
              <%= render @orders.old%>
          </tbody>
        </table>
      </div>

  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form'%>