config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  get 'sort', to: 'products#sort'
  resources :products do
    resources :orders, only: %i[new create]
  end

  resources :comments, only: %i[create update destroy]

  resources :orders, except: %i[index new create] do
    member do
      post 'state/:state', to: 'orders#state', as: 'state'
    end
  end
  get 'basket', to: 'orders#index'

  resource :my, only: %i[show update] do
    get 'personal'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :users, only: %i[show index]

  resources :categories, only: %i[show index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many_attached :images
  has_many :comments, as: :object, dependent: :destroy
  has_many :tags
  has_many :categories, through: :tags
  has_many :orders

  def all_tags
    categories.map(&:name).join(',')
  end

  def all_tags=(names)
    names = names.split(',').map { |name| name.strip.downcase }
    names.delete('')
    categories.clear
    categories << names.to_set.map do |name|
      Category.find_or_create_by!(name: name)
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def sort
    pp 'render sort'
    sort_name = params[:name]
    session['sort_type'] = if session['sort_name'] && session['sort_name'] == sort_name && session['sort_type'] != 'ASC'
                             'ASC'
                           else
                             'DESC'
                            end
    if %w[name created_at price].include?(sort_name)
      session['sort_name'] = sort_name
    end
    search_and_sort
  end

  # GET /products
  # GET /products.json

  def index
    pp 'render index'
    search_and_sort
  end

  # GET /products/1
  # GET /products/1.json
  def show
    s = session[:view_products]
    s ||= []
    s.push(@product.id)
    s.uniq!
    s.shift(@product.id) if s.count > 4
    session[:view_products] = s
    ids = []
    @product.categories.collect { |category| category.products.each { |product| ids.push product.id } }
    ids.uniq!
    ids.delete(@product.id)
    @like_products = Product.where(id: ids).limit(3)
  end

  # GET /products/new
  def new
    if current_user.id == 1
      @product = Product.new
    else
      redirect_back(fallback_location: root_path)
    end
  end

  # GET /products/1/edit
  def edit
    redirect_back(fallback_location: root_path) unless current_user.id == 1
  end

  # POST /products
  # POST /products.json
  def create
    # all_tags = params[:all_tags]
    if current_user.id == 1
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          # @product.all_tags = all_tags
          format.html { redirect_to @product, notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { render :index }
        # format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    if current_user.id == 1
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to @product, notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { render :index }
        # format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    if current_user.id == 1
      @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { render :index }
        # format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def search_and_sort
    @products = if params[:q].present?
                  Product.where('name LIKE ?', "%#{params[:q]}%")
                else
                  Product.all
    end
    unless session['sort_name'].nil?
      @products.order!("#{session['sort_name']} #{session['sort_type']}")
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :desc, :all_tags, :price, images: [])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |form| %>
<% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %>
      prohibited this product from being saved:</h2>

    <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Назва" %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "Категорії через кому" %><br>
    <%= form.text_field :all_tags %>
  </div>

  <div class="field">
    <%= form.label "Опис" %><br>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label "Укажіть ціну, грн."%><br>
    <%= form.text_field :price %>
  </div>
  <div class="field">
    <br>
    <label for="product_images" class="uploadButton">Загрузити фото</label>
    <%= form.file_field :images, accept: 'image/png,image/gif,image/jpeg', multiple: true %>
  </div>
  <div class="actions">
    <%= form.submit "Зберегти" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-12 col-md-4 col-lg-3 text-center justify-content-center">
  <div class="card" style="width: 100%;">
    <% if product.images.present?%>
      <%= image_tag product.images.first,width: 100, class: "card-img-top" %>
    <%end%>
    <div class="card-body text-center">
      <h5 class="card-title">
        <%= link_to product do %>
          <%= product.name %>
        <%end%>
      </h5>
      <p class="card-text price"><%= product.price %> грн.</p>
      <%= link_to "Замовити", new_product_order_path(product.id), class:'uploadButton ' %>
    </div>
  </div>
</div>

app/views/products/_products_line.html.erb
<% products.each do |product| %>
<tr>
  <td>
    <% if product.images.present?%>
      <%= image_tag product.images.first,width: 250 %>
    <%end%>
  </td>
  <td>
    <%= link_to product do %>
    <%= product.name %>
  <%end%>
</td>
<td><%= product.desc %></td>
<td><%= product.price %>
  грн.</td>
<% if user_signed_in? && current_user.id ==1 %>
  <td><%= link_to 'Edit', edit_product_path(product) %>
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%else%>
  <td>
    <%= link_to "Замовити", new_product_order_path(product.id), class:'uploadButton ' %>
  </td>
<%end%>
</tr>
<%end%>

app/views/products/_sort.html.erb
<div id="sort_line">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item <%if session[:sort_name]=="name"%>active<%end%>">
      <button type="button" name="button" class="nav-link sort" id="name">
Назва
    <%if session[:sort_name]=="name"%>
      <i class="<%if session[:sort_type]=="DESC"%>fa fa-angle-up<%else%>fa fa-angle-down <%end%>"></i>
    <%end%>

</button>
</li>
<li class="nav-item <%if session[:sort_name]=="price"%>active<%end%>">
  <button type="button" name="button" class="nav-link sort" id="price">
  Ціна
    <%if session[:sort_name]=="price"%>
  <i class="<%if session[:sort_type]=="DESC"%>fa fa-angle-up<%else%>fa fa-angle-down <%end%>"></i>
<%end%>
</button>
</li>
<li class="nav-item <%if session[:sort_name]=="created_at"%>active<%end%>">
  <button type="button" name="button" class="nav-link sort" id="created_at">

Дата створення
<%if session[:sort_name]=="created_at"%>
<i class="<%if session[:sort_type]=="DESC"%>fa fa-angle-up<%else%>fa fa-angle-down <%end%>"></i>
<%end%>
</button>
</li>
</ul>
</div>

app/views/products/edit.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <div id="formContent">
      <div class="fadeIn first">
        <h1>Редагувати товар</h1>
        </div>
          <%= render 'form', product: @product %>
        <div id="formFooter">
          <%= link_to 'Показати товар', @product %> |
          <%= link_to 'Повернутися назад', products_path %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center">
  <div class="otopright">
    <span class="icons" id="tcard">
      <i class="fa fa-columns"></i>
    </span>
    <span class="icons" id="ttable">
      <i class="fa fa-th-list"></i>
    </span>
  </div>
  Товари
</h1>

<% if params[:q].present? %>
  <div class="text-center">

    Результати за пошуком
    <b><%= params[:q]%></b>
  </div>
<%end%>

<div class="tcard active">

  <%=render "sort"%>
  <div id="products" class="row p-3 ">
    <%=render @products %>
  </div>
</div>

<div class="ttable">
  <table class="table table-striped table-active">
    <thead class="thead-dark">
      <tr>
      <th>Фото</th>
      <th>Назва</th>
      <th>Опис</th>
      <th>Ціна</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody id="products_line">

    <%=render "products/products_line", products:@products%>
  </tbody>
</table>
</div>

<script>
$("#tcard").on("click", function () {
  $(".ttable").removeClass("active");
  $(".tcard").addClass("active");
});
$("#ttable").on("click", function () {
  $(".tcard").removeClass("active");
  $(".ttable").addClass("active");
});
</script>

app/views/products/new.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <div id="formContent">
      <div class="fadeIn first">
        <h1>Добавити товар</h1>
        </div>
        <%= render 'form', product: @product %>
        <div id="formFooter">
        <%= link_to 'Повернутися назад', products_path %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="row p-2 p-md-3 p-lg-4">
  <div class="col-12 col-md-12 col-lg-9">
  <% if @product.images.present?%>
    <div class="row" >
    <div class="col-12 col-md-5 col-xl-4 text-center">
      <% @product.images.each do |image|  %>
        <%= image_tag image,width: 250 %>
      <%end%>
    </div>
  <%end%>
  <div class="col-12 col-md-7 col-xl-8">
    <div class="rozdil">
      <%if current_user.id == 1 %>
        <%= link_to 'Редагувати', edit_product_path(@product) %>
        |
      <%end%>
      <%= link_to 'Повернутися назад', products_path %>
    </div>
    <div class="rozdil">
      <strong>Назва:</strong>
      <%= @product.name %>
    </div>
    <div class="rozdil">
      <strong>Категорії:</strong>
      <%= tags(@product) %>
    </div>
    <div class="rozdil">
      <strong>Опис:</strong>
      <%= @product.desc %>
    </div>

    <div class="rozdil">
      <strong>Ціна:</strong>
      <span class="price">
        <%= @product.price %> грн.
      </span>
    </div>
    <div class="rozdil">
      <%= link_to "Замовити", new_product_order_path(@product.id), class:'uploadButton ' %>
    </div>
  </div>
    <div class="col-12 comments text-center">
    <h3>Коментарі</h3>
    <%= render @product.comments%>
    <%= render 'comments/form', object:@product %>
    </div>
  </div>
  </div>
  <div class="col-12 col-md-12 col-lg-3 text-center">
    <h3 class="text-center">Вам також сподобаються:</h3>
    <div class="row">
      <% @like_products.each do |product|%>
      <div class="card" style="width: 100%;">
        <% if product.images.present?%>
          <%= image_tag product.images.first,width: "100px", class: "card-img-top" %>
        <%end%>
        <div class="card-body text-center">
          <h5 class="card-title">
            <%= link_to product do %>
              <%= product.name %>
            <%end%>
          </h5>
          <p class="card-text price"><%= product.price %> грн.</p>
          <%= link_to "Замовити", new_product_order_path(product.id), class:'uploadButton ' %>
        </div>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/products/sort.js.erb
$('#products').empty();
$('#products').html('<%= j render @products%>');
$('#products_line').empty();
$('#products_line').html('<%= j render "products/products_line", products:@products%>');
$('#sort_line').empty();
$('#sort_line').html('<%= j render "products/sort"%>');