config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  get 'sort', to: 'products#sort'
  resources :products do
    resources :orders, only: %i[new create]
  end

  resources :comments, only: %i[create update destroy]

  resources :orders, except: %i[index new create] do
    member do
      post 'state/:state', to: 'orders#state', as: 'state'
    end
  end
  get 'basket', to: 'orders#index'

  resource :my, only: %i[show update] do
    get 'personal'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :users, only: %i[show index]

  resources :categories, only: %i[show index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<!-- Vertical navbar -->
<div class="vertical-nav bg-light active" id="sidebar">
  <div class="py-3 px-3 mb-4 bg-dark">
    <h5 class="title">МЕНЮ</h5>
  </div>

  <p class="text-gray font-weight-bold text-uppercase px-3 pb-4 mb-0">Основне</p>

  <ul class="nav flex-column bg-light mb-0">
    <li class="nav-item text-center">
      <%= form_tag(root_path, method: :get) do %>
      <div class="form-group" style="text-align: center">
        <%= text_field_tag :q,params[:q], class:"special", placeholder: "Натисніть для пошуку" %>
      </div>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to root_path, class:"nav-link" do %>
        <i class="fa fa-shopping-cart mr-2"></i>
        Товари
      <%end%>
    </li>
    <li class="nav-item">
      <%= link_to categories_path, class:"nav-link" do %>
          <i class="fa fa-tags mr-2"></i>
          Теги
      <%end%>
    </li>
    <li class="nav-item">
      <%=link_to basket_path, class:"nav-link" do %>
      <% if user_signed_in? && current_user.id ==1 %>
      <i class="fa fa-shopping-basket mr-2"></i>
      Активні замовлення

        <%else%>
        <i class="fa fa-shopping-basket mr-2"></i>
        Кошик
        <%end%>
      <%end%>
    </li>

  </ul>
  <br>
  <p class="text-gray font-weight-bold text-uppercase px-3 pb-4 mb-0">Профіль</p>
  <ul class="nav flex-column  bg-light mb-0" style="vertical-align:bottom;">
    <%if user_signed_in?%>
    <li class="nav-item">
      <%=link_to my_path, class:"nav-link" do %>
        <i class="fa fa-user mr-2"></i>
        Моя сторінка
      <%end%>
    </li>
    <li class="nav-item">
      <% if current_user.id ==1 %>
      <%= link_to new_product_path, class:"nav-link"  do%>
        <i class="fa fa-plus-circle mr-2"></i>
        Добавити продукт
      <%end%>
      <%end%>
    </li>
    <li class="nav-item">
      <%= link_to destroy_user_session_path, method: :delete, class:"nav-link" do %>
        <i class="fa fa-sign-out mr-2"></i>
        Вийти
      <%end%>
    </li>
    <%else%>
    <li class="nav-item">
      <%= link_to new_user_session_path,class:"nav-link" do %>
        <i class="fa fa-sign-in mr-2"></i>
        Вхід
      <%end%>
    </li>
    <li class="nav-item">
      <%= link_to new_user_registration_path,class:"nav-link" do %>
        <i class="fa fa-child mr-2"></i>
        Реєестрація
      <%end%>
    </li>
    <%end%>
  </ul>
</div>
<!-- End vertical navbar -->

<script type="text/javascript">

  $(function() {
    // Sidebar toggle behavior
    $('#sidebarCollapse').on('click', function() {
      $('#sidebar, #content').toggleClass('active');
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="page-content p-4 active" id="content">
      <!-- Toggle button -->
      <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-0"><small class="text-uppercase font-weight-bold">Меню</small></button>
    <%= yield %>
    </div>
  </body>
</html>